steps:

 ## build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops','.']
<<<<<<< HEAD

  ## push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push","gcr.io/cloud-builders/docker"]

  ## deploy container image to GKE
- name: "gcr.io/cloud-builders/docker"
  args:
    - run
    - --filename=gke.yml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=us-central1-c
    - --cluster=gke-gcp-devops
    - --namespace=gcp-devops-prod
=======
images:
- 'gcr.io/$PROJECT_ID/gcpdevops'
>>>>>>> d4ac1ecb5f9ca3a281b6945bd6af58823b8a3d2f
