apiVersion: apps/v1.2
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      matchLabels:
        app: gcp
    spec:
      containers: 
      - name: gcp-devops-gke
        image: gcr.io/gcp-devops-project/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT 
            values: "5000"
